/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VinSTTNorm.asrnormalizer;

import org.junit.Test;

import static org.junit.Assert.assertTrue;

public class OfflineNormalizerTest {
    @Test public void test() {
        VinFastVoiceControlAsrNormalizer vinFastVoiceControlAsrNormalizer = new VinFastVoiceControlAsrNormalizer();
        System.out.println(vinFastVoiceControlAsrNormalizer.normText("một hai ba"));
        assertTrue("someLibraryMethod should return 'true'", vinFastVoiceControlAsrNormalizer.normText("một hai ba").equals("123"));
    }
}
