/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VinSTTNorm.asrnormalizer;

import org.junit.Test;

import static org.junit.Assert.assertTrue;

public class VKeyAsrNormalizerTest {
    @Test public void test() {
        VKeyAsrNormalizer vKeyAsrNormalizer = new VKeyAsrNormalizer();
        System.out.println(vKeyAsrNormalizer.normText("một hai ba"));
        assertTrue("someLibraryMethod should return 'true'", vKeyAsrNormalizer.normText("một hai ba").equals("123"));
    }
}
